<?php
//TODO create view helper or method in View which will do something like this <?php echo $this->load('header',array('data'=>$data));// this load header.phtml template and pass $data to it
include "application/views/templates/header.phtml";
include "application/views/templates/menu.phtml";

echo $this->flashMessages(self::ERROR);
echo $this->flashMessages(self::WARNING);
echo $this->flashMessages(self::SUCCESS);

echo $this->html;
include "application/views/templates/footer.phtml";