<div class="container-narrow">
    <div class="masthead">
        <ul class="nav nav-pills pull-right">
            <li ><a href="/index/">Home</a></li>
            <li class="active"><a href="#">Map</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
        <h3 class="muted">Cities.loc</h3>
    </div>
    <hr>
    <form class="form-signin">
        <h2 class="form-signin-heading">Just simple examplhe...</h2>

        <p>Область</p>
        <select id="regions" class="selectpicker">
        </select>

        <p>Город</p>
        <select id="cities" class="selectpicker">
        </select>
    </form>
</div>