<div class="container-narrow">
    <div class="jumbotron">
        <div class="row-fluid marketing">
            <div class="span6">
                <h4>Обучение</h4>

                <p>Данный сайт создан в познавательных целях</p>

                <p>Здесь я пытаюсь изучать php, jQuery, html, mySql и некоторые другие везщи.</p>

                <p>Основной предмет изучения - паттерн MVC</p>

            </div>

            <div class="span6">
                <h4>Развлечение</h4>

                <p>В процессе раюоты и собственных "ляпов", обучение постепенно переходит в развлечение, что не может не
                    радовать</p>

            </div>
        </div>
    </div>