<!DOCTYPE html>

<html>
<head>

    <?php echo $this->headerTitle(); ?>
    <meta charset="utf-8">
    <meta name="description" content="Trying MVC, Twitter Bootstrap, AJAX, PHP, MySQL, Apache">
    <meta name="author" content="Artem Stepanishchev">

    <?php //TODO why do you use jquery 2? What about IE? ?>
    <script src="/js/jquery-2.1.1.min.js"></script>

    <script src="/js/jquery.min.js"></script>
    <?php //TODO why do you use jquery 2? What about IE? ?>
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/bootstrap-select.min.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/jquery-ui.min.js"></script>

    <script src="/js/validate.js"></script>
    <script src="/js/dialog.js"></script>
    <script src="/js/ajax.js"></script>


    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-select.min.css" rel="stylesheet">
    <link href="/css/jquery-ui.min.css" rel="stylesheet">
    <script type="text/javascript">
        //TODO do we need it on all pages?
        $(document).ready(function(e) {
            $('.selectpicker').selectpicker();
        });
    </script>
    <?php //TODO move it to css file ?>
    <style type="text/css">

        body {
            padding-bottom: 40px;
            overflow-y: scroll;
        }

        .container-narrow {
            position: relative;
            margin: 0 auto;
            max-width: 700px;
        }

        .deleteDialog {
            display: none;x
        }

        #errors div {
            color: red;
            margin-top: 7px;
            height: 10px;
        }

        .container-narrow >
        hr {
        }

        .jumbotron {
            padding: 0;
            background-color: #ffffff;
            align-content: center;
            text-align: center;
        }

        .jumbotron
        h1 {
            font-size: 72px;
            line-height: 1;
        }

        .jumbotron .btn-large {
            font-size: 21px;
            padding: 14px 24px;
        }

        .marketing {
            margin: 60px 0;
        }

        .marketing
        p + h4 {
            margin-top: 28px;
        }

        .signForm {
            max-width: 360px;
            padding: 29px 29px 29px;
            margin: 0 auto;;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        }

        .regionForm, .cityForm{
            max-width: 280px;
            padding: 29px 29px 29px;
            margin: 0 auto;;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
            box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        }

        .signForm .signForm-heading, .signForm .checkbox {
            margin-bottom: 10px;
        }

        .signForm input[type="text"], .signForm input[type="password"] {
            font-size: 16px;
            height: auto;
            width: 300px;
            margin-bottom: 15px;
            padding: 7px 9px;
        }

        .pagination {
            margin: 0;
            width: 450px;
        }

        .dark {
            position:absolute;
            bottom:0;
            left:0;
            top:0;
            width:700px;
            background-color: rgba(0,0,0,0.1);
            z-index: 99999;
        }

        .loader {
            width:10px;
            height:10px;
            position:absolute;
            left:48%;
            top:48%;
            }
    </style>
</head>
<body>
<div class="container-narrow">
