<!DOCTYPE html>
<html>
<head>
    <title>Cities.loc</title>

    <meta charset="utf-8">
    <meta name="description" content="Trying Twitter Bootstrap, AJAX, PHP, LAMP">
    <meta name="author" content="Artem Stepanishchev">

    <link href="public/css/bootstrap.css" rel="stylesheet">
    <script src="public/js/jquery.js"></script>
    <script src="public/js/ajax.js"></script>
    <script src="public/js/bootstrap.min.js"></script>
</head>
<body>