<!DOCTYPE html>

<html>
<head>
    <?php
    $rout = $_SERVER['REQUEST_URI'];
    $currentPage = ucfirst(explode('/', $rout)[1]) ? : 'Home';

    ?>
    <title><?= "Cities.loc: " . $currentPage ?></title>

    <meta charset="utf-8">
    <meta name="description" content="Trying Twitter Bootstrap, AJAX, PHP, LAMP">
    <meta name="author" content="Artem Stepanishchev">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <script src="/js/jquery.js"></script>
    <script src="/js/ajax.js"></script>
    <script src="/js/bootstrap.js"></script>
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
            overflow-y: scroll;
        }

        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }

        .container-narrow >
        hr {
            margin: 30px 0;
        }

        .jumbotron {
            margin: 60px 0;
            text-align: center;
        }

        .jumbotron
        h1 {
            font-size: 72px;
            line-height: 1;
        }

        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

        .marketing {
            margin: 60px 0;
        }

        .marketing
        p + h4 {
            margin-top: 28px;
        }
    </style>
</head>
<body>
