<div class="container-narrow">
    <div class="jumbotron">
        <p>Область</p>
        <select id="regions" class="selectpicker">
            <?php if (!empty($this->regions)): ?>
                <?php foreach ($this->regions as $region): ?>
                    <option value="<?php echo $region['id']; ?>"><?php echo $region['name']; ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>

        <p>Город</p>
        <select id="cities" class="selectpicker">

        </select>
    </div>
</div>
