<!DOCTYPE html>

<html>
<head>
    <?php
        //TODO WTF?? use $this->headTitle(); helper so in templates you can set head title like $this->title('My title'); and it will be displayed

        $rout = $_SERVER['REQUEST_URI'];
        $currentPage = ucfirst(explode('/', $rout)[1]) ? : 'Home';
    ?>
    <title><?= "Cities.loc: " . $currentPage;//TODO $this->headTitle(); ?></title>

    <meta charset="utf-8">
    <meta name="description" content="Trying MVC, Twitter Bootstrap, AJAX, PHP, MySQL, Apache">
    <meta name="author" content="Artem Stepanishchev">

    <link href="/css/bootstrap.css" rel="stylesheet">
    <script src="/js/jquery.js"></script>
    <script src="/js/ajax.js"></script>
    <script src="/js/bootstrap.js"></script>
    <style type="text/css">
        body {
            padding-top: 20px;
            padding-bottom: 40px;
            overflow-y: scroll;
        }

        .container-narrow {
            margin: 0 auto;
            max-width: 700px;
        }

        .container-narrow >
        hr {
        }

        .jumbotron {
            padding: 0;
            background-color: #ffffff;
            text-align: center;
        }

        .jumbotron
        h1 {
            font-size: 72px;
            line-height: 1;
        }

        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

        .marketing {
            margin: 60px 0;
        }

        .marketing
        p + h4 {
            margin-top: 28px;
        }
    </style>
</head>
<body>
<div class="container-narrow">
