
    <?php foreach ($cities as $city): ?>
        <tr>
            <td><?php echo $city['city_id']; ?></td>
            <td><?php echo $city['region_name']; ?></td>
            <td><?php echo $city['city_name']; ?></td>
            <td>
                <form method="POST" action="/admin/cities/edit/<?php echo $city['city_id']; ?>">
                    <button class="btn btn-info" name="city" value="<?php echo $city['city_id']; ?>">Edit</button>
                </form>
            </td>
            <td>
                <!-- Button trigger modal -->
                <button class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                    Delete
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span
                                        aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title" id="myModalLabel">Confirm deletion</h4>
                            </div>
                            <div class="modal-body">
                                Do you really want to delete this city?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                                <button type="button" class="cityDeletion btn btn-primary"
                                        value="<?php echo $city['city_id']; ?>">Yes
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>

