<div style="float : left; margin: 0 16px" class="navbar-form" role="search">
    <div class="input-group">
        <input type="text" class="form-control" placeholder="Search" id="srch-term">
        <div class="input-group-btn">
            <button class="btn btn-default" id="searchButton"><i class="glyphicon">Find</i></button>
        </div>
    </div>
</div>

<form method="POST" action="/admin/cities/add/">
    <button style="float: right; margin: 0 33px;" class="btn btn-success" name="city" value="add">Add new</button>
</form>
<br>
<br/>
<div class="container-narrow2" id="cities">
    <div class="dark">
        <div class="loader">
            <img src="/js/loader.gif">
        </div>
    </div>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th width="10%">#
                <div class="sort" data-type='city_id'><a id='up' href="#">&#9650;</a><a id='down' href="#">&#9660;</a>
                </div>
            </th>
            <th width="30%">Region name
                <div class="sort" data-type='region_name'><a id='up' href="#">&#9650;</a><a id='down' href="#">
                        &#9660;</a>
                </div>
            </th>
            <th width="50%">City name
                <div class="sort" data-type='city_name'><a style="color: #31b0d5;" id='up' href="#">&#9650;</a><a id='down' href="#">&#9660;</a>
                </div>
            </th>
            <th width="10%" colspan="2">Action</th>
        </tr>
        <tbody id="citiesTable">
        <?php require_once "cities_table.phtml"?>
        </tbody>
    </table>
</div>

<div id="citiesPagination">
    <?php require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . "pagination.phtml" ?>
</div>