<style>
    .user {
        float: right;
        margin: 0 10px;
    }

    .userDashboard {
        height: 20px;
    }
</style>

<?php use Core\Identifier\Identifier; ?>

<div class="userDashboard">
    <?php if(Identifier::identity() === 'admin'): ?>
        <a style="margin: 0 40px" href="/admin/">Administrator room</a>
    <?php endif;?>
    <p class="user"><?php echo $firstName .  " " . $lastName; ?></p>
</div>
<hr>
