<div class="container-narrow2">
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <col width="10%">
            <col width="20%">
            <col width="30%">
            <col width="40%">
            <th>#</th>
            <th>First name</th>
            <th>Last name</th>
            <th>Email</th>
        </tr>

        <?php foreach ($users as $user): ?>
            <tr>
                <?php foreach ($user as $data): ?>
                    <?php echo "<td>$data</td>"; ?>

                <?php endforeach; ?>
            </tr>
        <?php endforeach; ?>
    </table>
</div>