<?php use App\Managers\MapManager; ?>
<?php
    //TODO use the same template as for edit region
    $regionName = MapManager::getRegionById($regionId)

?>

<div class="jumbotron">
    <p class="lead">Region #<?php echo $regionId; ?> information editing </p>
    <form method="POST" class="regionForm" id="regionForm" action="/admin/regions/edit/<?php echo $regionId; ?>">
        <input class="form-control input-block-level" name="region_name" type="text"  placeholder="Region name"
               value="<?= $regionName ?>">
        <div id="errors"></div>
        </br>
        <button class="btn btn-primary" name="region_id" value="<?php echo $regionId; ?>" id="editionSubmit" type="submit">Edit</button>
    </form>
</div>