<form method="POST" action="/admin/regions/add/">
    <button style="float: right; margin: 0 33px;" class="btn btn-success" name="region" value="add">Add new</button>
</form>
<br>
<br/>

<div class="container-narrow2" id="regionsTable">
    <?php require_once "regions_table.phtml" //TODO use view helper to render  ?>
</div>

<div id="regionsPagination">
    <?php require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . "pagination.phtml" ?>
</div>