<?php use App\Managers\MapManager; ?>
<?php $regions = MapManager::getRegions(); ?>

<div class="jumbotron">
    <p class="lead">New city addition</p>
    <form method="POST" class="cityForm" id="cityForm" action="/admin/add">
        <select name="region_id" class="selectpicker">
            <?php if (!empty($regions)): ?>
                <?php foreach ($regions as $region): ?>
                    <option value="<?php echo $region['region_id']; ?>"><?php echo $region['region_name']; ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
        </br>
        </br>

        <input name="city_name" type="text" class="input-block-level" placeholder="City name">
        <div id="errors"></div>
        </br>
        <button class="btn btn-primary" id="additionSubmit" type="submit">Add</button>
    </form>
</div>