<?php use App\Managers\MapManager; ?>
<?php
    //TODO use the same template as for edit city
    $regions = MapManager::getRegions();

?>

<div class="jumbotron">
    <p class="lead">New city addition</p>
    <form method="POST" class="cityForm" id="cityForm" action="/admin/cities/add">
        <select name="region_id" class="selectpicker">
            <?php if (!empty($regions)): ?>
                <?php foreach ($regions as $region): ?>
                    <option value="<?php echo $region['region_id']; ?>"><?php echo $region['region_name']; ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
        <br />
        <br />

        <input class="form-control input-block-level" name="city_name" type="text"  placeholder="City name">
        <div id="errors"></div>
        <br />
        <input class="form-control input-block-level" name="city_latitude" type="text"  placeholder="City latitude">
        <br />
        <input class="form-control input-block-level" name="city_longitude" type="text"  placeholder="City longitude">
        <div id="errors"></div>
        <br />
        <button class="btn btn-primary" id="additionSubmit" type="submit">Add</button>
    </form>
</div>