<div class="jumbotron">
    <p class="lead">New region addition</p>
    <form method="POST" class="regionForm" id="regionForm" action="/admin/regions/add">
        <input name="region_name" type="text" class="input-block-level" placeholder="Region name">
        <div id="errors"></div>
        </br>
        <button class="btn btn-primary" id="additionSubmit" type="submit">Add</button>
    </form>
</div>