<table class="table table-striped table-bordered table-hover">
    <tr>
        <col width="10%">
        <col width="40%">
        <col width="40%">
        <col width="10%">
        <th>#</th>
        <th>Region name</th>
        <th>City name</th>
        <th colspan="2">Action</th>

    </tr>
    <?php foreach ($cities as $city): ?>
        <tr>
            <?php foreach ($city as $data): ?>
                <?php echo "<td>$data</td>"; ?>
            <?php endforeach; ?>
            <td>
                <form method="GET" action="/admin/edit/">
                    <button class="btn btn-info" name="city" value="<?php echo $city['city_id']; ?>">edit</button>
                </form>
            </td>
            <td>
                <form method="POST" action="/admin/delete/">
                    <button class="btn btn-danger" name="city" value="<?php echo $city['city_id']; ?>">delete</button>
                </form>
            </td>
        </tr>
    <?php endforeach; ?>
</table>