<form method="POST" action="/admin/cities/add/">
    <button style="float: right" class="btn btn-success" name="city" value="add">Add new</button>
</form>
</br>
</br>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <col width="10%">
        <col width="40%">
        <col width="40%">
        <col width="10%">
        <th>#</th>
        <th>Region name</th>
        <th>City name</th>
        <th colspan="2">Action</th>

    </tr>
    <?php foreach ($cities as $city): ?>
        <tr>
            <?php foreach ($city as $data): ?>
                <?php echo "<td>$data</td>"; ?>
            <?php endforeach; ?>
            <td>
                <form method="POST" action="/admin/cities/edit/<?php echo $city['city_id']; ?>">
                    <button class="btn btn-info" name="city" value="<?php echo $city['city_id']; ?>">edit</button>
                </form>
            </td>
            <td>
                <button class="cityDelete btn btn-danger" name="city" value="<?php echo $city['city_id']; ?>">delete
                </button>
            </td>
        </tr>
    <?php endforeach; ?>
    <div id="deleteDialog"> Do you really want to delete this city?</div>
</table>
<?php echo $this->citiesPagination(); ?>