<?php use App\Managers\MapManager; ?>
<?php $cityName = MapManager::getCityById($cityId); ?>
<?php $cords = MapManager::getCityCordsById($cityId); ?>
<?php $cityLatitude = $cords['latitude']; ?>
<?php $cityLongitude = $cords['longitude']; ?>

<?php $regions = MapManager::getRegions(); ?>

<div class="jumbotron">
    <p class="lead">City #<?php echo $cityId; ?> information editing </p>

    <form method="POST" class="cityForm" id="cityForm" action="/admin/cities/edit/<?php echo $cityId; ?>">
        <select name="region_id" class="selectpicker">
            <?php if (!empty($regions)): ?>
                <?php foreach ($regions as $region): ?>
                    <option value="<?php echo $region['region_id']; ?>"><?php echo $region['region_name']; ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
        <br/>
        <br/>
        <input class="form-control input-block-level" name="city_name" type="text" placeholder="City name"
               value="<?= $cityName ?>">
    </form>
    <br/>

    <div id="frame">
        <div id="map_canvas"></div>
    </div>
    <br/>
    <button class="btn btn-primary" name="city_id" value="<?php echo $cityId; ?>" id="editionSubmit" type="submit">
        Edit
    </button>

</div>