<div id="regionsPage">
    <form method='POST' action="/admin/regions/add">
        <button style="float: right" class="btn btn-success">Add new</button>
    </form>
    </br>
    </br>
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <col width="10%">
            <col width="80%">
            <col width="10%">
            <th>#</th>
            <th>Region name</th>
            <th colspan="2">Action</th>
        </tr>
        <?php foreach ($regions as $region): ?>
            <tr>
                <?php foreach ($region as $data): ?>
                    <?php echo "<td>$data</td>"; ?>
                <?php endforeach; ?>
                <td>
                    <form method="POST" action="/admin/regions/edit/<?php echo $region['region_id']; ?>">
                        <button class="btn btn-info" name="region" value="<?php echo $region['region_id']; ?>">edit
                        </button>
                    </form>
                </td>
                <td>
                    <button class="regionDelete btn btn-danger" name="region"
                            value="<?php echo $region['region_id']; ?>">delete
                    </button>
                </td>
            </tr>
        <?php endforeach; ?>
        <div id="deleteDialog"> Do you really want to delete this region?</div>
    </table>
</div>
<?php echo $this->regionsPagination(); ?>