<div class="dark">
    <div class="loader">
        <img src="/js/loader.gif">
    </div>
</div>
<table class="table table-striped table-bordered table-hover">
    <tr>
        <col width="10%">
        <col width="80%">
        <col width="10%">
        <th>#</th>
        <th>Region name</th>
        <th colspan="2">Action</th>
    </tr>
    <?php foreach ($regions as $region): ?>
        <tr>
            <?php foreach ($region as $data): ?>
                <?php echo "<td>$data</td>"; ?>
            <?php endforeach; ?>
            <td>
                <form method="POST" action="/admin/cities/edit/<?php echo $region['region_id']; ?>">
                    <button class="btn btn-info" name="city" value="<?php echo $region['region_id']; ?>">Edit</button>
                </form>
            </td>
            <td>
                <!-- Button trigger modal -->
                <button class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                    Delete
                </button>

                <!-- Modal -->
                <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
                     aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"><span
                                        aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                <h4 class="modal-title" id="myModalLabel">Confirm deletion</h4>
                            </div>
                            <div class="modal-body">
                                Do you really want to delete this region?
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
                                <button type="button" class="regionDeletion btn btn-primary"
                                        value="<?php echo $city['city_id']; ?>">Yes
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
