<table class="table table-striped table-bordered table-hover">
    <tr>
        <col width="10%">
        <col width="80%">
        <col width="10%">
        <th>#</th>
        <th>Region name</th>
        <th colspan="2">Action</th>
    </tr>
    <?php foreach ($regions as $region): ?>
        <tr>
                <?php foreach ($region as $data): ?>
                    <?php echo "<td>$data</td>"; ?>
                <?php endforeach; ?>
                <td>
                    <form method="GET" action="/admin/edit/">
                        <button class="btn btn-info" name="region" value="<?php echo $region['region_id']; ?>">edit</button>
                    </form>
                </td>
                <td>
                    <form method="POST" action="/admin/delete/">
                        <button class="btn btn-danger" name="region" value="<?php echo $region['region_id']; ?>">delete</button>
                    </form>
                </td>

        </tr>
    <?php endforeach; ?>
</table>