<div class="jumbotron">
    <p>Область</p>
    <select id="regions" class="selectpicker">
        <?php if (!empty($regions)): ?>
            <?php foreach ($regions as $region): ?>
                <option value="<?php echo $region['region_id']; ?>"><?php echo $region['region_name']; ?></option>
            <?php endforeach; ?>
        <?php endif; ?>
    </select>

    <p>Город</p>
    <select id="cities" class="selectpicker">

    </select>
</div>