<div class="jumbotron">
    <h2 class="form-signup-heading">You can join us right now!</h2>
    <p class="lead">Fill some personal information</p>
    <?php
    $first_name = !empty($_POST['first_name']) ? $_POST['first_name'] : "";
    $last_name = !empty($_POST['last_name']) ? $_POST['last_name'] : "";
    $email = !empty($_POST['email']) ? $_POST['email'] : "";
    ?>
    <form method="POST" class="signForm" id="registerForm" action="/registration/">
        <input name="first_name" type="text" class="input-block-level" placeholder="First name"
               value="<?= $first_name ?>">
        <input name="last_name" type="text" class="input-block-level" placeholder="Last name"
               value="<?= $last_name ?>">
        <input name="email" type="text" class="input-block-level" placeholder="Email" value="<?= $email ?>">
        <input name="password" id="password" type="password" class="input-block-level" placeholder="Password">
        <input name="password_confirm" type="password" class="input-block-level" placeholder="Password confirm">
        </br>
        <button class="btn btn-large btn-primary" id="registrationSubmit" type="submit">Sing up</button>
    </form>
</div>