<!-- I have to use styles here :( -->
<style type="text/css">
    .form-signup {
        max-width: 360px;
        padding: 29px 29px 29px;
        margin: 0 auto;;
        background-color: #fff;
        border: 1px solid #e5e5e5;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        -moz-box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
        box-shadow: 0 1px 2px rgba(0, 0, 0, .05);
    }

    .form-signup .form-signup-heading, .form-signup .checkbox {
        margin-bottom: 10px;
    }

    .form-signup input[type="text"], .form-signup input[type="password"] {
        font-size: 16px;
        height: auto;
        width: 300px;
        margin-bottom: 15px;
        padding: 7px 9px;
    }
</style>
<div class="jumbotron">
    <h2 class="form-signup-heading">Fill some personal information</h2>
    <?php
    $first_name = !empty($_POST['first_name']) ? $_POST['first_name'] : "";
    $second_name = !empty($_POST['second_name']) ? $_POST['second_name'] : "";
    $email = !empty($_POST['email']) ? $_POST['email'] : "";
    $password = !empty($_POST['password']) ? $_POST['password'] : "";
    $password_confirm = !empty($_POST['password_confirm']) ? $_POST['password_confirm'] : "";
    ?>
    <form method="POST" class="form-signup" action="/registration/">
        <input name="first_name" type="text" class="input-block-level" placeholder="First name"
               value="<?= $first_name ?>">
        <input name="second_name" type="text" class="input-block-level" placeholder="Second name"
               value="<?= $second_name ?>">
        <input name="email" type="text" class="input-block-level" placeholder="Email" value="<?= $email ?>">
        <input name="password" type="password" class="input-block-level" placeholder="Password"
               value="<?= $password ?>">
        <input name="password_confirm" type="password" class="input-block-level" placeholder="Password confirm"
               value="<?= $password_confirm ?>">
        <button class="btn btn-large btn-primary" type="submit">Sing up</button>
    </form>
</div>